### ISSUE TITLE
这个库有问题吧？ 什么内容都没有

### ISSUE THREAD

**Issue by codering** [fis-components/lodash._getnative#1]
@2betop 这个库有问题吧？ 什么内容都没有。

**Comment by 2betop** [comment]
嗯，有问题

**Comment by 2betop** [comment]
修复了

**Comment by codering** [comment]
@2betop 顺便问个rc组件使用问题，
1. 里面组件有用到`reuqire("../util")`类似的依赖，但是它真正要找的却是`require("../util/index")`，我用mod.js就会出现无法找到模块的错误. 
2. 全编译成es5, 从学习的角度，可读性就差了.

**Comment by codering** [comment]
原来是直接通过npm install的，第二点当我没说 :)

**Comment by 2betop** [comment]
这个你升级下 fis3-hook-commonjs 就支持了

**Comment by codering** [comment]
ok!
